### PR TITLE
Add PMDA SciPy paper data

### LINKED ISSUE #39: add PMDA SciPy paper data
add https://figshare.com/articles/Molecular_Dynamics_trajectories_of_membrane_protein_YiiP/8202149

### PR DESCRIPTION
**Pull request by VOD555**
Fixes #39 

Changes made in this Pull Request:

- add yiip_equilibrium.py which contains fetch_yiip_equilibrium_short and fetch_yiip_equilibrium_long.
- add docs for yiip_equilibrium.py

PR Checklist
==========
- [x] Tests?
- [x] Docs?
- [ ] CHANGELOG updated?

### CODE REVIEW

**Comment by VOD555** [comment]
@orbeckst Please check the PR. The tests in the test_datasets.py are deselected, so the coverage decreases.

**Comment by orbeckst** [comment]
Can you do the merge? I can't do it from mobile.

**Comment by VOD555** [comment]
Merged.

**Comment by VOD555** [comment]
@orbeckst No, I don't have the authority to merge the PR.

**Pull request merged**
